### PR TITLE
Expanded search query

### PR DESCRIPTION
**Pull request by kndm**
Changed the query so that it checks the search term against more fields.

Can definitely clean up the query string creation further. Just a quick change for now.

### CODE REVIEW

**Comment by andylolz** [comment]
Wowzers – thanks! Let me give this a go.

> Can definitely clean up the query string creation further. Just a quick change for now.

No worries, this is fine.

**Comment by kndm** [comment]
My pleasure @andylolz 

Look forward to hearing back from you soon! :)

**Comment by andylolz** [comment]
Thanks again, @kndm! I tested to check these are doing what they should be, and it looks like you’ve cracked it! Great work.

I also noticed that I should be escaping the search string before adding it to the URL, which I guess is a fairly bad bug. I’ve made a ticket: #97.

Would you mind if I modified your PR in the following ways:

 * Add `organization_title`, because I think that could be a really useful one
 * Remove all URL searches, because I think they’ll mostly throw up false positives
 * Remove `license_id`, because again I’m not sure how often users will want to search on license, so I think it might just add noise.

If you’re happy with that, I’ll make those changes, add a changelog entry and merge. If you don’t agree, let me know and we can think about it a bit more!

**Comment by matmaxgeds** [comment]
Thanks @andylolz - good spots, `organization_title` we meant to include in the first place, and looking at the URL returns e.g. all the aiddata ones for the logo's I think you are right. I also wanted to check if you were ok with keeping the email addresses (I think they help) but you might feel that is another source of too many false positives? Agreed also on`license_id`, anyone that far into IATI data is also capable of figuring it out themselves. New PR on it's way.

**Comment by andylolz** [comment]
Great – sounds like we’re in total agreement. I’m fine with keeping emails in there.

If you or @kndm push to this branch, it’ll just update this existing pull request.

**Comment by kndm** [comment]
Pushed the changes requested :)

**Comment by andylolz** [comment]
Looks good – thanks!

I’ve referenced you both in the changelog – hope that’s okay.

**Comment by matmaxgeds** [comment]
Ace, thanks @andylolz

**Comment by andylolz** [comment]
I made a couple of other unrelated updates, so I’ve pushed v1.3.0 to the chrome webstore and firefox addon store.

**Comment by andylolz** [comment]
I made a couple of other unrelated updates, so I’ve pushed v1.3.0 to the chrome webstore and firefox addon store.

**Pull request merged**
